export interface Country {
    code: string;
    flag: string;
    dial_code: string;
    name: string;
}

export const COUNTRIES: Country[] = [
    { code: 'AF', flag: '🇦🇫', dial_code: '+93', name: 'Afghanistan' },
    { code: 'AL', flag: '🇦🇱', dial_code: '+355', name: 'Albania' },
    { code: 'DZ', flag: '🇩🇿', dial_code: '+213', name: 'Algeria' },
    { code: 'AS', flag: '🇦🇸', dial_code: '+1-684', name: 'American Samoa' },
    { code: 'AD', flag: '🇦🇩', dial_code: '+376', name: 'Andorra' },
    { code: 'AO', flag: '🇦🇴', dial_code: '+244', name: 'Angola' },
    { code: 'AI', flag: '🇦🇮', dial_code: '+1-264', name: 'Anguilla' },
    { code: 'AG', flag: '🇦🇬', dial_code: '+1-268', name: 'Antigua and Barbuda' },
    { code: 'AR', flag: '🇦🇷', dial_code: '+54', name: 'Argentina' },
    { code: 'AM', flag: '🇦🇲', dial_code: '+374', name: 'Armenia' },
    { code: 'AW', flag: '🇦🇼', dial_code: '+297', name: 'Aruba' },
    { code: 'AU', flag: '🇦🇺', dial_code: '+61', name: 'Australia' },
    { code: 'AT', flag: '🇦🇹', dial_code: '+43', name: 'Austria' },
    { code: 'AZ', flag: '🇦🇿', dial_code: '+994', name: 'Azerbaijan' },
    { code: 'BS', flag: '🇧🇸', dial_code: '+1-242', name: 'Bahamas' },
    { code: 'BH', flag: '🇧🇭', dial_code: '+973', name: 'Bahrain' },
    { code: 'BD', flag: '🇧🇩', dial_code: '+880', name: 'Bangladesh' },
    { code: 'BB', flag: '🇧🇧', dial_code: '+1-246', name: 'Barbados' },
    { code: 'BY', flag: '🇧🇾', dial_code: '+375', name: 'Belarus' },
    { code: 'BE', flag: '🇧🇪', dial_code: '+32', name: 'Belgium' },
    { code: 'BZ', flag: '🇧🇿', dial_code: '+501', name: 'Belize' },
    { code: 'BJ', flag: '🇧🇯', dial_code: '+229', name: 'Benin' },
    { code: 'BM', flag: '🇧🇲', dial_code: '+1-441', name: 'Bermuda' },
    { code: 'BT', flag: '🇧🇹', dial_code: '+975', name: 'Bhutan' },
    { code: 'BO', flag: '🇧🇴', dial_code: '+591', name: 'Bolivia' },
    { code: 'BA', flag: '🇧🇦', dial_code: '+387', name: 'Bosnia and Herzegovina' },
    { code: 'BW', flag: '🇧🇼', dial_code: '+267', name: 'Botswana' },
    { code: 'BR', flag: '🇧🇷', dial_code: '+55', name: 'Brazil' },
    { code: 'BN', flag: '🇧🇳', dial_code: '+673', name: 'Brunei' },
    { code: 'BG', flag: '🇧🇬', dial_code: '+359', name: 'Bulgaria' },
    { code: 'BF', flag: '🇧🇫', dial_code: '+226', name: 'Burkina Faso' },
    { code: 'BI', flag: '🇧🇮', dial_code: '+257', name: 'Burundi' },
    { code: 'KH', flag: '🇰🇭', dial_code: '+855', name: 'Cambodia' },
    { code: 'CM', flag: '🇨🇲', dial_code: '+237', name: 'Cameroon' },
    { code: 'CA', flag: '🇨🇦', dial_code: '+1', name: 'Canada' },
    { code: 'CV', flag: '🇨🇻', dial_code: '+238', name: 'Cape Verde' },
    { code: 'KY', flag: '🇰🇾', dial_code: '+1-345', name: 'Cayman Islands' },
    { code: 'CF', flag: '🇨🇫', dial_code: '+236', name: 'Central African Republic' },
    { code: 'TD', flag: '🇹🇩', dial_code: '+235', name: 'Chad' },
    { code: 'CL', flag: '🇨🇱', dial_code: '+56', name: 'Chile' },
    { code: 'CN', flag: '🇨🇳', dial_code: '+86', name: 'China' },
    { code: 'CO', flag: '🇨🇴', dial_code: '+57', name: 'Colombia' },
    { code: 'KM', flag: '🇰🇲', dial_code: '+269', name: 'Comoros' },
    { code: 'CG', flag: '🇨🇬', dial_code: '+242', name: 'Congo' },
    { code: 'CD', flag: '🇨🇩', dial_code: '+243', name: 'Congo, Democratic Republic' },
    { code: 'CK', flag: '🇨🇰', dial_code: '+682', name: 'Cook Islands' },
    { code: 'CR', flag: '🇨🇷', dial_code: '+506', name: 'Costa Rica' },
    { code: 'CI', flag: '🇨🇮', dial_code: '+225', name: 'Cote d\'Ivoire' },
    { code: 'HR', flag: '🇭🇷', dial_code: '+385', name: 'Croatia' },
    { code: 'CU', flag: '🇨🇺', dial_code: '+53', name: 'Cuba' },
    { code: 'CY', flag: '🇨🇾', dial_code: '+357', name: 'Cyprus' },
    { code: 'CZ', flag: '🇨🇿', dial_code: '+420', name: 'Czech Republic' },
    { code: 'DK', flag: '🇩🇰', dial_code: '+45', name: 'Denmark' },
    { code: 'DJ', flag: '🇩🇯', dial_code: '+253', name: 'Djibouti' },
    { code: 'DM', flag: '🇩🇲', dial_code: '+1-767', name: 'Dominica' },
    { code: 'DO', flag: '🇩🇴', dial_code: '+1-809', name: 'Dominican Republic' },
    { code: 'EC', flag: '🇪🇨', dial_code: '+593', name: 'Ecuador' },
    { code: 'EG', flag: '🇪🇬', dial_code: '+20', name: 'Egypt' },
    { code: 'SV', flag: '🇸🇻', dial_code: '+503', name: 'El Salvador' },
    { code: 'GQ', flag: '🇬🇶', dial_code: '+240', name: 'Equatorial Guinea' },
    { code: 'ER', flag: '🇪🇷', dial_code: '+291', name: 'Eritrea' },
    { code: 'EE', flag: '🇪🇪', dial_code: '+372', name: 'Estonia' },
    { code: 'ET', flag: '🇪🇹', dial_code: '+251', name: 'Ethiopia' },
    { code: 'FK', flag: '🇫🇰', dial_code: '+500', name: 'Falkland Islands' },
    { code: 'FO', flag: '🇫🇴', dial_code: '+298', name: 'Faroe Islands' },
    { code: 'FJ', flag: '🇫🇯', dial_code: '+679', name: 'Fiji' },
    { code: 'FI', flag: '🇫🇮', dial_code: '+358', name: 'Finland' },
    { code: 'FR', flag: '🇫🇷', dial_code: '+33', name: 'France' },
    { code: 'GF', flag: '🇬🇫', dial_code: '+594', name: 'French Guiana' },
    { code: 'PF', flag: '🇵🇫', dial_code: '+689', name: 'French Polynesia' },
    { code: 'GA', flag: '🇬🇦', dial_code: '+241', name: 'Gabon' },
    { code: 'GM', flag: '🇬🇲', dial_code: '+220', name: 'Gambia' },
    { code: 'GE', flag: '🇬🇪', dial_code: '+995', name: 'Georgia' },
    { code: 'DE', flag: '🇩🇪', dial_code: '+49', name: 'Germany' },
    { code: 'GH', flag: '🇬🇭', dial_code: '+233', name: 'Ghana' },
    { code: 'GI', flag: '🇬🇮', dial_code: '+350', name: 'Gibraltar' },
    { code: 'GR', flag: '🇬🇷', dial_code: '+30', name: 'Greece' },
    { code: 'GL', flag: '🇬🇱', dial_code: '+299', name: 'Greenland' },
    { code: 'GD', flag: '🇬🇩', dial_code: '+1-473', name: 'Grenada' },
    { code: 'GP', flag: '🇬🇵', dial_code: '+590', name: 'Guadeloupe' },
    { code: 'GU', flag: '🇬🇺', dial_code: '+1-671', name: 'Guam' },
    { code: 'GT', flag: '🇬🇹', dial_code: '+502', name: 'Guatemala' },
    { code: 'GN', flag: '🇬🇳', dial_code: '+224', name: 'Guinea' },
    { code: 'GW', flag: '🇬🇼', dial_code: '+245', name: 'Guinea-Bissau' },
    { code: 'GY', flag: '🇬🇾', dial_code: '+592', name: 'Guyana' },
    { code: 'HT', flag: '🇭🇹', dial_code: '+509', name: 'Haiti' },
    { code: 'HN', flag: '🇭🇳', dial_code: '+504', name: 'Honduras' },
    { code: 'HK', flag: '🇭🇰', dial_code: '+852', name: 'Hong Kong' },
    { code: 'HU', flag: '🇭🇺', dial_code: '+36', name: 'Hungary' },
    { code: 'IS', flag: '🇮🇸', dial_code: '+354', name: 'Iceland' },
    { code: 'IN', flag: '🇮🇳', dial_code: '+91', name: 'India' },
    { code: 'ID', flag: '🇮🇩', dial_code: '+62', name: 'Indonesia' },
    { code: 'IR', flag: '🇮🇷', dial_code: '+98', name: 'Iran' },
    { code: 'IQ', flag: '🇮🇶', dial_code: '+964', name: 'Iraq' },
    { code: 'IE', flag: '🇮🇪', dial_code: '+353', name: 'Ireland' },
    { code: 'IL', flag: '🇮🇱', dial_code: '+972', name: 'Israel' },
    { code: 'IT', flag: '🇮🇹', dial_code: '+39', name: 'Italy' },
    { code: 'JM', flag: '🇯🇲', dial_code: '+1-876', name: 'Jamaica' },
    { code: 'JP', flag: '🇯🇵', dial_code: '+81', name: 'Japan' },
    { code: 'JO', flag: '🇯🇴', dial_code: '+962', name: 'Jordan' },
    { code: 'KZ', flag: '🇰🇿', dial_code: '+7', name: 'Kazakhstan' },
    { code: 'KE', flag: '🇰🇪', dial_code: '+254', name: 'Kenya' },
    { code: 'KI', flag: '🇰🇮', dial_code: '+686', name: 'Kiribati' },
    { code: 'KP', flag: '🇰🇵', dial_code: '+850', name: 'Korea, North' },
    { code: 'KR', flag: '🇰🇷', dial_code: '+82', name: 'Korea, South' },
    { code: 'KW', flag: '🇰🇼', dial_code: '+965', name: 'Kuwait' },
    { code: 'KG', flag: '🇰🇬', dial_code: '+996', name: 'Kyrgyzstan' },
    { code: 'LA', flag: '🇱🇦', dial_code: '+856', name: 'Laos' },
    { code: 'LV', flag: '🇱🇻', dial_code: '+371', name: 'Latvia' },
    { code: 'LB', flag: '🇱🇧', dial_code: '+961', name: 'Lebanon' },
    { code: 'LS', flag: '🇱🇸', dial_code: '+266', name: 'Lesotho' },
    { code: 'LR', flag: '🇱🇷', dial_code: '+231', name: 'Liberia' },
    { code: 'LY', flag: '🇱🇾', dial_code: '+218', name: 'Libya' },
    { code: 'LI', flag: '🇱🇮', dial_code: '+423', name: 'Liechtenstein' },
    { code: 'LT', flag: '🇱🇹', dial_code: '+370', name: 'Lithuania' },
    { code: 'LU', flag: '🇱🇺', dial_code: '+352', name: 'Luxembourg' },
    { code: 'MO', flag: '🇲🇴', dial_code: '+853', name: 'Macao' },
    { code: 'MG', flag: '🇲🇬', dial_code: '+261', name: 'Madagascar' },
    { code: 'MW', flag: '🇲🇼', dial_code: '+265', name: 'Malawi' },
    { code: 'MY', flag: '🇲🇾', dial_code: '+60', name: 'Malaysia' },
    { code: 'MV', flag: '🇲🇻', dial_code: '+960', name: 'Maldives' },
    { code: 'ML', flag: '🇲🇱', dial_code: '+223', name: 'Mali' },
    { code: 'MT', flag: '🇲🇹', dial_code: '+356', name: 'Malta' },
    { code: 'MH', flag: '🇲🇭', dial_code: '+692', name: 'Marshall Islands' },
    { code: 'MQ', flag: '🇲🇶', dial_code: '+596', name: 'Martinique' },
    { code: 'MR', flag: '🇲🇷', dial_code: '+222', name: 'Mauritania' },
    { code: 'MU', flag: '🇲🇺', dial_code: '+230', name: 'Mauritius' },
    { code: 'MX', flag: '🇲🇽', dial_code: '+52', name: 'Mexico' },
    { code: 'FM', flag: '🇫🇲', dial_code: '+691', name: 'Micronesia' },
    { code: 'MD', flag: '🇲🇩', dial_code: '+373', name: 'Moldova' },
    { code: 'MC', flag: '🇲🇨', dial_code: '+377', name: 'Monaco' },
    { code: 'MN', flag: '🇲🇳', dial_code: '+976', name: 'Mongolia' },
    { code: 'ME', flag: '🇲🇪', dial_code: '+382', name: 'Montenegro' },
    { code: 'MS', flag: '🇲🇸', dial_code: '+1-664', name: 'Montserrat' },
    { code: 'MA', flag: '🇲🇦', dial_code: '+212', name: 'Morocco' },
    { code: 'MZ', flag: '🇲🇿', dial_code: '+258', name: 'Mozambique' },
    { code: 'MM', flag: '🇲🇲', dial_code: '+95', name: 'Myanmar' },
    { code: 'NA', flag: '🇳🇦', dial_code: '+264', name: 'Namibia' },
    { code: 'NR', flag: '🇳🇷', dial_code: '+674', name: 'Nauru' },
    { code: 'NP', flag: '🇳🇵', dial_code: '+977', name: 'Nepal' },
    { code: 'NL', flag: '🇳🇱', dial_code: '+31', name: 'Netherlands' },
    { code: 'NC', flag: '🇳🇨', dial_code: '+687', name: 'New Caledonia' },
    { code: 'NZ', flag: '🇳🇿', dial_code: '+64', name: 'New Zealand' },
    { code: 'NI', flag: '🇳🇮', dial_code: '+505', name: 'Nicaragua' },
    { code: 'NE', flag: '🇳🇪', dial_code: '+227', name: 'Niger' },
    { code: 'NG', flag: '🇳🇬', dial_code: '+234', name: 'Nigeria' },
    { code: 'NU', flag: '🇳🇺', dial_code: '+683', name: 'Niue' },
    { code: 'NF', flag: '🇳🇫', dial_code: '+672', name: 'Norfolk Island' },
    { code: 'MK', flag: '🇲🇰', dial_code: '+389', name: 'North Macedonia' },
    { code: 'NO', flag: '🇳🇴', dial_code: '+47', name: 'Norway' },
    { code: 'OM', flag: '🇴🇲', dial_code: '+968', name: 'Oman' },
    { code: 'PK', flag: '🇵🇰', dial_code: '+92', name: 'Pakistan' },
    { code: 'PW', flag: '🇵🇼', dial_code: '+680', name: 'Palau' },
    { code: 'PS', flag: '🇵🇸', dial_code: '+970', name: 'Palestine' },
    { code: 'PA', flag: '🇵🇦', dial_code: '+507', name: 'Panama' },
    { code: 'PG', flag: '🇵🇬', dial_code: '+675', name: 'Papua New Guinea' },
    { code: 'PY', flag: '🇵🇾', dial_code: '+595', name: 'Paraguay' },
    { code: 'PE', flag: '🇵🇪', dial_code: '+51', name: 'Peru' },
    { code: 'PH', flag: '🇵🇭', dial_code: '+63', name: 'Philippines' },
    { code: 'PL', flag: '🇵🇱', dial_code: '+48', name: 'Poland' },
    { code: 'PT', flag: '🇵🇹', dial_code: '+351', name: 'Portugal' },
    { code: 'PR', flag: '🇵🇷', dial_code: '+1-787', name: 'Puerto Rico' },
    { code: 'QA', flag: '🇶🇦', dial_code: '+974', name: 'Qatar' },
    { code: 'RE', flag: '🇷🇪', dial_code: '+262', name: 'Reunion' },
    { code: 'RO', flag: '🇷🇴', dial_code: '+40', name: 'Romania' },
    { code: 'RU', flag: '🇷🇺', dial_code: '+7', name: 'Russia' },
    { code: 'RW', flag: '🇷🇼', dial_code: '+250', name: 'Rwanda' },
    { code: 'KN', flag: '🇰🇳', dial_code: '+1-869', name: 'Saint Kitts and Nevis' },
    { code: 'LC', flag: '🇱🇨', dial_code: '+1-758', name: 'Saint Lucia' },
    { code: 'VC', flag: '🇻🇨', dial_code: '+1-784', name: 'Saint Vincent and the Grenadines' },
    { code: 'WS', flag: '🇼🇸', dial_code: '+685', name: 'Samoa' },
    { code: 'SM', flag: '🇸🇲', dial_code: '+378', name: 'San Marino' },
    { code: 'ST', flag: '🇸🇹', dial_code: '+239', name: 'Sao Tome and Principe' },
    { code: 'SA', flag: '🇸🇦', dial_code: '+966', name: 'Saudi Arabia' },
    { code: 'SN', flag: '🇸🇳', dial_code: '+221', name: 'Senegal' },
    { code: 'RS', flag: '🇷🇸', dial_code: '+381', name: 'Serbia' },
    { code: 'SC', flag: '🇸🇨', dial_code: '+248', name: 'Seychelles' },
    { code: 'SL', flag: '🇸🇱', dial_code: '+232', name: 'Sierra Leone' },
    { code: 'SG', flag: '🇸🇬', dial_code: '+65', name: 'Singapore' },
    { code: 'SK', flag: '🇸🇰', dial_code: '+421', name: 'Slovakia' },
    { code: 'SI', flag: '🇸🇮', dial_code: '+386', name: 'Slovenia' },
    { code: 'SB', flag: '🇸🇧', dial_code: '+677', name: 'Solomon Islands' },
    { code: 'SO', flag: '🇸🇴', dial_code: '+252', name: 'Somalia' },
    { code: 'ZA', flag: '🇿🇦', dial_code: '+27', name: 'South Africa' },
    { code: 'ES', flag: '🇪🇸', dial_code: '+34', name: 'Spain' },
    { code: 'LK', flag: '🇱🇰', dial_code: '+94', name: 'Sri Lanka' },
    { code: 'SD', flag: '🇸🇩', dial_code: '+249', name: 'Sudan' },
    { code: 'SR', flag: '🇸🇷', dial_code: '+597', name: 'Suriname' },
    { code: 'SZ', flag: '🇸🇿', dial_code: '+268', name: 'Swaziland' },
    { code: 'SE', flag: '🇸🇪', dial_code: '+46', name: 'Sweden' },
    { code: 'CH', flag: '🇨🇭', dial_code: '+41', name: 'Switzerland' },
    { code: 'SY', flag: '🇸🇾', dial_code: '+963', name: 'Syria' },
    { code: 'TW', flag: '🇹🇼', dial_code: '+886', name: 'Taiwan' },
    { code: 'TJ', flag: '🇹🇯', dial_code: '+992', name: 'Tajikistan' },
    { code: 'TZ', flag: '🇹🇿', dial_code: '+255', name: 'Tanzania' },
    { code: 'TH', flag: '🇹🇭', dial_code: '+66', name: 'Thailand' },
    { code: 'TG', flag: '🇹🇬', dial_code: '+228', name: 'Togo' },
    { code: 'TO', flag: '🇹🇴', dial_code: '+676', name: 'Tonga' },
    { code: 'TT', flag: '🇹🇹', dial_code: '+1-868', name: 'Trinidad and Tobago' },
    { code: 'TN', flag: '🇹🇳', dial_code: '+216', name: 'Tunisia' },
    { code: 'TR', flag: '🇹🇷', dial_code: '+90', name: 'Turkey' },
    { code: 'TM', flag: '🇹🇲', dial_code: '+993', name: 'Turkmenistan' },
    { code: 'TC', flag: '🇹🇨', dial_code: '+1-649', name: 'Turks and Caicos Islands' },
    { code: 'TV', flag: '🇹🇻', dial_code: '+688', name: 'Tuvalu' },
    { code: 'UG', flag: '🇺🇬', dial_code: '+256', name: 'Uganda' },
    { code: 'UA', flag: '🇺🇦', dial_code: '+380', name: 'Ukraine' },
    { code: 'AE', flag: '🇦🇪', dial_code: '+971', name: 'United Arab Emirates' },
    { code: 'GB', flag: '🇬🇧', dial_code: '+44', name: 'United Kingdom' },
    { code: 'US', flag: '🇺🇸', dial_code: '+1', name: 'United States' },
    { code: 'UY', flag: '🇺🇾', dial_code: '+598', name: 'Uruguay' },
    { code: 'UZ', flag: '🇺🇿', dial_code: '+998', name: 'Uzbekistan' },
    { code: 'VU', flag: '🇻🇺', dial_code: '+678', name: 'Vanuatu' },
    { code: 'VE', flag: '🇻🇪', dial_code: '+58', name: 'Venezuela' },
    { code: 'VN', flag: '🇻🇳', dial_code: '+84', name: 'Vietnam' },
    { code: 'VG', flag: '🇻🇬', dial_code: '+1-284', name: 'Virgin Islands, British' },
    { code: 'VI', flag: '🇻🇮', dial_code: '+1-340', name: 'Virgin Islands, U.S.' },
    { code: 'YE', flag: '🇾🇪', dial_code: '+967', name: 'Yemen' },
    { code: 'ZM', flag: '🇿🇲', dial_code: '+260', name: 'Zambia' },
    { code: 'ZW', flag: '🇿🇼', dial_code: '+263', name: 'Zimbabwe' },
];
